# Generated by Django 3.1.3 on 2020-12-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efirstname', models.CharField(max_length=100)),
                ('elastname', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('phonenumber', models.CharField(max_length=12)),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
    ]
