# Generated by Django 3.1.3 on 2020-12-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0004_auto_20201203_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignproject',
            name='Employee',
        ),
        migrations.AddField(
            model_name='assignproject',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpSearch.employee'),
        ),
        migrations.RemoveField(
            model_name='assignproject',
            name='Project',
        ),
        migrations.AddField(
            model_name='assignproject',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpSearch.project'),
        ),
    ]
