# Generated by Django 3.1.3 on 2020-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0005_auto_20201203_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignproject',
            name='Employee',
        ),
        migrations.AddField(
            model_name='assignproject',
            name='Employee',
            field=models.ManyToManyField(to='EmpSearch.Employee'),
        ),
        migrations.RemoveField(
            model_name='assignproject',
            name='Project',
        ),
        migrations.AddField(
            model_name='assignproject',
            name='Project',
            field=models.ManyToManyField(to='EmpSearch.Project'),
        ),
    ]
