# Generated by Django 3.1.3 on 2020-12-03 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0009_auto_20201204_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Project',
        ),
        migrations.AddField(
            model_name='project',
            name='Employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EmpSearch.employee'),
            preserve_default=False,
        ),
    ]
