# Generated by Django 3.1.3 on 2020-12-03 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0010_auto_20201204_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='per', to='EmpSearch.employee'),
        ),
    ]
