# Generated by Django 3.1.3 on 2020-12-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0012_auto_20201204_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Employee',
        ),
        migrations.AddField(
            model_name='project',
            name='Employee',
            field=models.ManyToManyField(to='EmpSearch.Employee'),
        ),
    ]
