# Generated by Django 3.1.3 on 2020-12-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0013_auto_20201204_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Employee',
        ),
        migrations.AddField(
            model_name='project',
            name='Employee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EmpSearch.employee'),
            preserve_default=False,
        ),
    ]
