# Generated by Django 3.1.3 on 2020-12-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0016_auto_20201204_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Project',
        ),
        migrations.AddField(
            model_name='employee',
            name='Project',
            field=models.ManyToManyField(to='EmpSearch.Project'),
        ),
    ]
