# Generated by Django 3.1.3 on 2020-12-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0019_auto_20201204_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Project',
        ),
        migrations.AddField(
            model_name='employee',
            name='Project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='EmpSearch.project'),
            preserve_default=False,
        ),
    ]
