# Generated by Django 3.1.3 on 2020-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpSearch', '0021_auto_20201204_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='Project',
            field=models.ManyToManyField(to='EmpSearch.Project'),
        ),
    ]
